### PR TITLE
[WIP] basic key generation using rpgp

### PR DESCRIPTION
**Pull request by dignifiedquire**
This expects rpgp to be installed using the following work flow

```
> git clone https://github.com/dignifiedquire/rpgp
> cd rpgp
> cd pgp-ffi
> make
```

After that run `meson && ninja` and things should build. 

Current  state: 
- ~~Tests are not happy with the public key for some reason~~
- ~~Fails to `free(user_id)`~~
- Stress tests are passing, and the cmdline cli boots up
- All required things are in `master` of rpgp

### CODE REVIEW

**Comment by hpk42** [comment]
the makefile needs to use '-f' for removing: rm -f libpgp.h
so that it doesn't error out if the files does not exist.

**Comment by hpk42** [comment]
followed the steps and at "make" time eventually it failed at compiling rand: https://gist.github.com/hpk42/78acd6415d580329a8821d96cd61e9ba

**Comment by dignifiedquire** [comment]
hmm, that is odd, can you try running `cargo update && cargo clean && cargo test`? also can you make sure you have the latest commit on `extern-c` branch checked out?

**Comment by dignifiedquire** [comment]
(I forced to that branch earlier today, so you might have an old version of it)

**Comment by r10s** [comment]
cool :) great! happy to test this out.

maybe we can keep the old code a bit and use a `#ifdef RPGP` or so - then we can merge it and iterate from there without the need to have an android/whatever build-system ready just _now_.

**Comment by hpk42** [comment]
the cargo-update,clean,test seems to progressed further but compile now fails elsewhere https://gist.github.com/hpk42/8e603e075e63493295c96cb15b0a5c59

**Comment by dignifiedquire** [comment]
what rust version are you using?

**Comment by hpk42** [comment]
rust-c --version gives "rustc 1.31.1 (b6c32da9b 2018-12-18)"

**Comment by dignifiedquire** [comment]
closing in favor of #591

**Pull request closed without merging**
