### PR TITLE
probe imap STARTTLS on ports 993 and 143

### LINKED ISSUE #552: Improve automatic configuration
Delta Chat autoconfiguration seems to be smart enough, sadly it is a bit broken.
My server doesn't provide an autoconfig xml but it uses well know addresses and ports, so when I input "myusername@nauta.cu" and my password and leave empty all other fields, Delta Chat automatically try to use my email as user and "imap.nauta.cu"/"smtp.nauta.cu" for the IMAP/SMTP server, also the port is automatically "detected" based on the protocol and security method used, but the only thing that is broken is the IMAP Security setting(and probably SMTP Security also), I have to manually set it to STARTTLS, since Delta Chat only tries SSL and shows a toast with an error of ssl connection failed "imap.nauta.cu:993" instead of trying STARTTLS. This is the only thing preventing users to have an awesome user experience and providing only email and password without having to open advanced settings and filling all field since they never gonna guess that only disabling Security will work.
This have nothing to do with autoconfig xml files which is not provided by this server, that is only needed if the server use not well know ports  imo, and a MUA like thunderbird is able to automatically detect this settings without the autoconfig xml, as shown in the screenshots.

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.100
- Screenshots:

auto-config

autoconfig-results

### PR DESCRIPTION
**Pull request by r10s**
this pr improves the autoconfiguration by probing STARTTLS on port 993 after probing SSL on 993.

if both fail, both are retried with using only the local part of the mail as the login name.

closes #552

### CODE REVIEW

**Comment by adbenitez** [comment]
what about of plain in 143??

**Comment by r10s** [comment]
> what about of plain in 143

well, now as the logic with the username is simplified, we could rather easily this test.

however, i am not sure if there are many real-life-providers out there that do support none of STARTTLS and SSL on 993.

might also be a question of security when accepting PLAIN as a default or as a fallback, not sure.

**Comment by adbenitez** [comment]
Nauta server support STARTTLS and plain, both on 143

**Comment by r10s** [comment]
afaik also posteo (well-known german provider with focus on privacy) uses STARTTLS on port 143, so it makes probably some sense to test this as well. however, i would not test for PLAIN.

**Comment by adbenitez** [comment]
I think it is ok without PLAIN
 :+1:

**Pull request merged**
