### PR TITLE
Fallback to Copy/Delete if Move not possible

### PR DESCRIPTION
**Pull request by t-oster**
The mailserver of @Ji-eF does not work with the used MOVE command, so messages are left in the INBOX (see deltachat/deltachat-android#307).
I found the hint in the source that many mailservers don't support the MOVE operation so we should fallback to COPY/DELETE.
This is my first attempt to do that. The copy part works, however the delete part does not.

EDITED. See below

The String from the test-server is:
```
IMAP-Capabilities: IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS MULTIAPPEND UNSELECT IDLE CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS QUOTA

### CODE REVIEW

**Comment by t-oster** [comment]
Since I would need the `rfc724_mid` for using `mrimap_delete_msg` I just copied the relevant parts to delete the message. However I am not sure this works and it is correct that way.

**Comment by r10s** [comment]
at a first glace, this looks good to me.

**Comment by r10s** [comment]
> Do we have to update any IDs in the DC database, because the copy is a new message and the original one is deleted?

yes, but this is already done by the caller (it is also needed for move)

> This is my first attempt to do that. The copy part works, however the delete part does not.

Does it work for you in the edited version? the code looks as it should work :)

**Comment by t-oster** [comment]
Yes, it works on the Server of @Ji-eF. However Messages which are from an non-DC initiated chat are not moved (part of https://github.com/deltachat/deltachat-android/issues/307). You can merge this and I will have a look into the other problem

**Comment by t-oster** [comment]
(there is no other problem. This fixes https://github.com/deltachat/deltachat-android/issues/307

**Pull request merged**
