### PR TITLE
Neppgp ssl mac

### PR DESCRIPTION
**Pull request by ralphtheninja**
Supersedes https://github.com/deltachat/deltachat-core/pull/346

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@flub We're getting further. It compiles now but get compile errors https://travis-ci.org/deltachat/deltachat-node/jobs/437662050#L5384-L5414

**Comment by ralphtheninja** [comment]
@flub Works! https://travis-ci.org/deltachat/deltachat-node/builds/437948683 Maybe we could clean this branch up a bit? The history looks a bit messy.

**Comment by hpk42** [comment]
looks to me as if a "squash-merge" is fine here.

**Comment by ralphtheninja** [comment]
> looks to me as if a "squash-merge" is fine here.

Ok, lets try it. Yolo.

**Pull request merged**
