### PR TITLE
Link to LICENSE

### PR DESCRIPTION
**Pull request by ralphtheninja**
Using the same style in `deltachat-node`.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
We use the `star year - present` in all `level` repositories to avoid having to update the copyright years all the time.

**Comment by r10s** [comment]
sounds like a good idea, and sounds very good to me, but i am not a lawyer. 
have you seen the <year>-present format in other projects. are they usual?

**Comment by ralphtheninja** [comment]
@r10s Nope I haven't.

**Comment by ralphtheninja** [comment]
@r10s I kept the years as is and just added a link to the license.

**Comment by r10s** [comment]
yes, this is easier to merge :)
wrt the copyright years, maybe also @jankass has an idea ...

**Pull request merged**
