### PR TITLE
Add experimental support rPGP 

### PR DESCRIPTION
**Pull request by dignifiedquire**
This expects rpgp to be installed using the following work flow

```
> git clone https://github.com/dignifiedquire/rpgp
> cd rpgp/pgp-ffi
> make install
```

After that run `meson && ninja` and things should build. 

Current  state: 
- Stress tests are passing, and the cmdline cli boots up
- All required things are in `master` of rpgp

### CODE REVIEW

**Comment by r10s** [comment]
changed the switch to DC_USE_RPGP - if defined, rpgp is used from the code side.

DC_USE_RPGP is not defined by default - systems that support it, should define it.

@flub can we get a switch for so easily to meson? the switch should define DC_USE_RPGP and do a `rpgp = cc.find_library('rpgp')` as in the current meson file. if undefined, everything should work as just now.
if that is too complicated, i would suggest to comment the changes in meson out for now; if needed they can be enabled then.

apart from the meson-thing, this pr looks good; it does basically nothing when DC_USE_RPGP is not defined.

the next step would be to get it run on android then :)

**Comment by flub** [comment]
whoa, i pushed to this same branch.  magic

**Comment by flub** [comment]
I realise there's no instructions on how to use that.  Invoke meson with `meson builddir -Drpgp=true` (or do the `meson configure -Drpgp=true` thing in an existing builddir)

**Comment by dignifiedquire** [comment]
Update: all builds of `pgp-ffi` should be done using `--release --features nightly` and a nightly compiler ideally to ensure best perf + security available

**Comment by r10s** [comment]
@dignifiedquire from my side, this can be merged :)

**Pull request merged**
