### PR TITLE
Add LibreSSL <2.7.0 support

### LINKED ISSUE #419: Fails to build with LibreSSL: src/dc_openssl.c:122: undefined reference to `OPENSSL_init_ssl'
This report should be submitted to NetPGP [as well], I think. But it seems like not very alive...
deltachat-core v0.24.1
LibreSSL 2.6.5

```
~/projects/deltachat-core/builddir/ ninja
[5/58] Compiling C object 'libs/netpgp/libs@netpgp@@netpgp@sta/src_misc.c.o'.
../libs/netpgp/src/openssl_crypto.c: In function ‘pgp_dsa_verify’:
../libs/netpgp/src/openssl_crypto.c:427:5: warning: implicit declaration of function ‘DSA_SIG_set0’; did you mean ‘DSA_SIG_new’? [-Wimplicit-function-declaration]
     DSA_SIG_set0(osig,
     ^~~~~~~~~~~~
     DSA_SIG_new
../libs/netpgp/src/openssl_crypto.c:432:5: warning: implicit declaration of function ‘DSA_set0_pqg’ [-Wimplicit-function-declaration]
     DSA_set0_pqg(odsa,
     ^~~~~~~~~~~~
../libs/netpgp/src/openssl_crypto.c:437:5: warning: implicit declaration of function ‘DSA_set0_key’; did you mean ‘RSA_check_key’? [-Wimplicit-function-declaration]
     DSA_set0_key(odsa,
     ^~~~~~~~~~~~
     RSA_check_key
../libs/netpgp/src/openssl_crypto.c: In function ‘pgp_rsa_public_decrypt’:
../libs/netpgp/src/openssl_crypto.c:483:5: warning: implicit declaration of function ‘RSA_set0_key’; did you mean ‘RSA_check_key’? [-Wimplicit-function-declaration]
     RSA_set0_key(orsa,
     ^~~~~~~~~~~~
     RSA_check_key
../libs/netpgp/src/openssl_crypto.c: In function ‘pgp_rsa_private_encrypt’:
../libs/netpgp/src/openssl_crypto.c:524:5: warning: implicit declaration of function ‘RSA_set0_factors’; did you mean ‘RSA_set_method’? [-Wimplicit-function-declaration]
     RSA_set0_factors(orsa,
     ^~~~~~~~~~~~~~~~
     RSA_set_method
../libs/netpgp/src/openssl_crypto.c: In function ‘pgp_rsa_generate_keypair’:
../libs/netpgp/src/openssl_crypto.c:777:5: warning: implicit declaration of function ‘RSA_get0_key’; did you mean ‘RSA_check_key’? [-Wimplicit-function-declaration]
     RSA_get0_key(rsa, &_n, &_e, &_d);
     ^~~~~~~~~~~~
     RSA_check_key
../libs/netpgp/src/openssl_crypto.c:793:5: warning: implicit declaration of function ‘RSA_get0_factors’; did you mean ‘RSA_get_method’? [-Wimplicit-function-declaration]
     RSA_get0_factors(rsa, &_p, &_q);
     ^~~~~~~~~~~~~~~~
     RSA_get_method
../libs/netpgp/src/openssl_crypto.c: In function ‘pgp_dsa_sign’:
../libs/netpgp/src/openssl_crypto.c:914:5: warning: implicit declaration of function ‘DSA_SIG_get0’; did you mean ‘DSA_SIG_new’? [-Wimplicit-function-declaration]
     DSA_SIG_get0(dsasig, &pr, &ps);
     ^~~~~~~~~~~~
     DSA_SIG_new
[40/58] Compiling C object 'src/src@@deltachat@sha/dc_mimeparser.c.o'.
../src/dc_openssl.c: In function ‘dc_openssl_init’:
../src/dc_openssl.c:122:6: warning: implicit declaration of function ‘OPENSSL_init_ssl’; did you mean ‘OPENSSL_init’? [-Wimplicit-function-declaration]
      OPENSSL_init_ssl(0, NULL);
      ^~~~~~~~~~~~~~~~
      OPENSSL_init
[56/58] Linking target src/libdeltachat.so.0.24.1.
FAILED: src/libdeltachat.so.0.24.1 
cc  -o src/libdeltachat.so.0.24.1 'src/src@@deltachat@sha/dc_aheader.c.o' 'src/src@@deltachat@sha/dc_apeerstate.c.o' 'src/src@@deltachat@sha/dc_array.c.o' 'src/src@@deltachat@sha/dc_chat.c.o' 'src/src@@deltachat@sha/dc_chatlist.c.o' 'src/src@@deltachat@sha/dc_contact.c.o' 'src/src@@deltachat@sha/dc_dehtml.c.o' 'src/src@@deltachat@sha/dc_hash.c.o' 'src/src@@deltachat@sha/dc_imap.c.o' 'src/src@@deltachat@sha/dc_job.c.o' 'src/src@@deltachat@sha/dc_key.c.o' 'src/src@@deltachat@sha/dc_keyring.c.o' 'src/src@@deltachat@sha/dc_loginparam.c.o' 'src/src@@deltachat@sha/dc_lot.c.o' 'src/src@@deltachat@sha/dc_context.c.o' 'src/src@@deltachat@sha/dc_configure.c.o' 'src/src@@deltachat@sha/dc_e2ee.c.o' 'src/src@@deltachat@sha/dc_imex.c.o' 'src/src@@deltachat@sha/dc_keyhistory.c.o' 'src/src@@deltachat@sha/dc_log.c.o' 'src/src@@deltachat@sha/dc_qr.c.o' 'src/src@@deltachat@sha/dc_receive_imf.c.o' 'src/src@@deltachat@sha/dc_securejoin.c.o' 'src/src@@deltachat@sha/dc_mimefactory.c.o' 'src/src@@deltachat@sha/dc_mimeparser.c.o' 'src/src@@deltachat@sha/dc_msg.c.o' 'src/src@@deltachat@sha/dc_openssl.c.o' 'src/src@@deltachat@sha/dc_param.c.o' 'src/src@@deltachat@sha/dc_pgp.c.o' 'src/src@@deltachat@sha/dc_saxparser.c.o' 'src/src@@deltachat@sha/dc_simplify.c.o' 'src/src@@deltachat@sha/dc_smtp.c.o' 'src/src@@deltachat@sha/dc_sqlite3.c.o' 'src/src@@deltachat@sha/dc_stock.c.o' 'src/src@@deltachat@sha/dc_strbuilder.c.o' 'src/src@@deltachat@sha/dc_strencode.c.o' 'src/src@@deltachat@sha/dc_token.c.o' 'src/src@@deltachat@sha/dc_tools.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libdeltachat.so.0 libs/netpgp/libnetpgp.a /usr/lib64/libz.so /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libsasl2.so /usr/lib64/libsqlite3.so -L/usr/lib64 -letpan -Wl,-O1 -Wl,--as-needed -lz -lssl -lcrypto -ldb-6.0 -lz -Wl,--end-group -pthread '-Wl,-rpath,$ORIGIN/../libs/netpgp' -Wl,-rpath-link,/home/stefan/projects/deltachat-core/builddir/libs/netpgp  
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: src/src@@deltachat@sha/dc_openssl.c.o: in function `dc_openssl_init':
/home/stefan/projects/deltachat-core/builddir/../src/dc_openssl.c:122: undefined reference to `OPENSSL_init_ssl'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_dsa_verify':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:427: undefined reference to `DSA_SIG_set0'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:432: undefined reference to `DSA_set0_pqg'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:437: undefined reference to `DSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_rsa_public_decrypt':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:483: undefined reference to `RSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_rsa_private_encrypt':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:518: undefined reference to `RSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:524: undefined reference to `RSA_set0_factors'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_rsa_private_check':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:555: undefined reference to `RSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:560: undefined reference to `RSA_set0_factors'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_rsa_private_decrypt':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:610: undefined reference to `RSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:615: undefined reference to `RSA_set0_factors'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_rsa_public_encrypt':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:664: undefined reference to `RSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_rsa_generate_keypair':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:777: undefined reference to `RSA_get0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:793: undefined reference to `RSA_get0_factors'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libs/netpgp/libnetpgp.a(src_openssl_crypto.c.o): in function `pgp_dsa_sign':
/home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:900: undefined reference to `DSA_set0_pqg'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:905: undefined reference to `DSA_set0_key'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/stefan/projects/deltachat-core/builddir/../libs/netpgp/src/openssl_crypto.c:914: undefined reference to `DSA_SIG_get0'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by steils**
Fixes #419

### CODE REVIEW

**Comment by r10s** [comment]
looks good to me.

**Comment by r10s** [comment]
@steils very happy to work with you :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja this may also affect the mac desktop build - isn't mac using LibreSSL?

Correct. But `meson` doesn't seem to pick it up.

**Comment by flub** [comment]
thanks @steils !

**Comment by steils** [comment]
Thanks to you for the quick review! :-)

**Pull request merged**
