### PR TITLE
The "minor changes" PR

### PR DESCRIPTION
**Pull request by Ampli-fier**
The only **fix** is:  swap arguments for the _addcontact_ command in cmdline.
The rest is just cosmetics :)

### CODE REVIEW

**Comment by r10s** [comment]
You're becoming a C-Expert :)

**Comment by Ampli-fier** [comment]
Ha ha :)
Actually, my current attempts to compile C-code do no end any more in **segmentation faults** ... sometimes ...

**Comment by r10s** [comment]
:)

**Comment by Ampli-fier** [comment]
I noticed an error in my commit for swapping arguments for addcontact.

In fact, the first parameter, which is the name is optional and must be mentioned first but with brackets [ ].
So this is the correct syntax for the two lines in cmdline.c:

`"addcontact [<name>] <addr>\n"`

`ret = safe_strdup("ERROR: Arguments [<name>] <addr> expected.");`

Can you please update the code accordingly?

**Comment by r10s** [comment]
> Can you please update the code accordingly?

done so, see https://github.com/deltachat/deltachat-core/commit/f14c518b70995dcbdf49f86db5208d93f1b1cb6c (being around there anyway :)

**Pull request merged**
