### PR TITLE
New backup import-export functions for lesser memory consumption

### PR DESCRIPTION
**Pull request by csb0730**
Characteristics:
- new backup file format which uses SQLITE sqlar format
- messenger db is stored as blob in archive
- all blob files are stored with dir name in archive
- no need for vacuum of huge backup file at import
- memory consumption drops to approx 2x backup file size
- export is done only in new sqlar file format
- import is done with old and new file format (automatic detection)

Comments welcome

### CODE REVIEW

**Comment by csb0730** [comment]
Detected some problems in path handling at device at import!

Will update the PR next days.

**Comment by r10s** [comment]
please note, that we're moving to rust currently, see https://github.com/deltachat/deltachat-core-rust . if things work out, the c-core will probably go away at all. just now, the c-core is frozen, so we do not add new features there unless absolutely necessary.

**Comment by csb0730** [comment]
Not really a problem.
Changes are not so big and C code can serve as code template and moved to rust.

**Comment by csb0730** [comment]
@dignifiedquire 
Maybe You can have a look meanwhile?

**Comment by r10s** [comment]
@csb0730 i think, the current task is to get the rust-core stable at all. if this is done, we think about new features :)

**Comment by r10s** [comment]
closing this pr for reasons metioned above

**Pull request closed without merging**
