### PR TITLE
avoid typedef warnings

### PR DESCRIPTION
**Pull request by r10s**
this pr tries to avoid warnings that may be emmited wrt typedef's

see https://github.com/deltachat/deltachat-node/issues/223

i am not totally sure why the warning appears, however with https://github.com/deltachat/deltachat-core/pull/508/commits/eb25158ed7c6f9f046d0dd1d6e7a0dcdf00c58c1 i've separated strucuture definitions and typedefs (as already done for deltachat.h to allow opaque structures).
maybe this fixes the warning, or, at least make things a bit clearer.

Closes https://github.com/deltachat/deltachat-node/issues/223

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@r10s You can check full log here if it helps https://api.travis-ci.org/v3/job/476667984/log.txt

**Comment by r10s** [comment]
tested the changes with gcc 7.3.0 that ships with ubuntu 18.04 and with ndk-build default compiler - no warnings there :)

**Comment by ralphtheninja** [comment]
Works fine now! :tada:

**Comment by r10s** [comment]
great :)

**Pull request merged**
